In [1]:
import torch

In [7]:
batch_size = 1
seq_len = 3
input_size = 4
hidden_size = 2
num_layers = 1

In [3]:
cell = torch.nn.RNNCell(input_size = input_size, hidden_size = hidden_size)

dataset = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(batch_size, hidden_size)

In [5]:
for idx, input in enumerate(dataset):
    print('- ' * 20, idx, '-' * 20)
    print('Input size: ', input.shape)
    
    hidden = cell(input, hidden)
    
    print('outputs size: ', hidden.shape)
    print(hidden)

- - - - - - - - - - - - - - - - - - - -  0 --------------------
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[ 0.8865, -0.8922]], grad_fn=<TanhBackward0>)
- - - - - - - - - - - - - - - - - - - -  1 --------------------
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[ 0.6116, -0.8016]], grad_fn=<TanhBackward0>)
- - - - - - - - - - - - - - - - - - - -  2 --------------------
Input size:  torch.Size([1, 4])
outputs size:  torch.Size([1, 2])
tensor([[ 0.9305, -0.9211]], grad_fn=<TanhBackward0>)


In [9]:
cell = torch.nn.RNN(input_size = input_size, hidden_size = hidden_size, num_layers = num_layers)
inputs = torch.randn(seq_len, batch_size, input_size)
hidden = torch.zeros(num_layers, batch_size, hidden_size)

In [10]:
out, hidden = cell(inputs, hidden)

In [12]:
print("Output size" , out.shape)
print("Output:", out)
print('Hidden size: ', hidden.shape)
print('Hidden: ', hidden)

Output size torch.Size([3, 1, 2])
Output: tensor([[[-0.0913, -0.6764]],

        [[ 0.5097,  0.5233]],

        [[ 0.3687, -0.0938]]], grad_fn=<StackBackward0>)
Hidden size:  torch.Size([1, 1, 2])
Hidden:  tensor([[[ 0.3687, -0.0938]]], grad_fn=<StackBackward0>)
